name: ChokuRando Release
run-name: "Release build for ChokuRando"
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        type: string
      releaseNotes:
        description: Release notes
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        type: [ { rid: 'linux-x64', image: 'ubuntu-latest ' },  { rid: 'osx-arm64', image: 'macos-latest' }, { rid:  'osx-x64', image: 'macos-latest ' },  { rid: 'win-x64', image: 'windows-latest' } ]
    runs-on: ${{ matrix.type.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Publish
        shell: pwsh
        run: |
          dotnet publish ChokuRando/ChokuRando.csproj -c Release -f net8.0 -r ${{ matrix.type.rid }} --self-contained /p:DebugType=None /p:DebugSymbols=false /p:PublishSingleFile=true
          Compress-Archive -Path ChokuRando/bin/Release/net8.0/${{ matrix.type.rid }}}/publish/ -DestinationPath ChokuRando/bin/Release/net8.0/${{ matrix.type.rid }}/ChokuRando-${{ matrix.type.rid }}.zip
      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.type.rid }}-zip
          path: ChokuRando/bin/Release/net8.0/${{ matrix.type.rid }}/ChokuRando-${{ matrix.type.rid }}.zip
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Download Linux zip
        uses: actions/download-artifact@v4.1.8
        with:
          name: linux-x64-zip
      - name: Download Apple Silicon zip
        uses: actions/download-artifact@v4.1.8
        with:
          name: osx-arm64-zip
      - name: Download Intel macOS zip
        uses: actions/download-artifact@v4.1.8
        with:
          name: osx-x64-zip
      - name: Download Windows zip
        uses: actions/download-artifact@v4.1.8
        with:
          name: windows-x64-zip
      - name: Move and rename artifacts
        shell: pwsh
        run: |
          New-Item -Type Directory -Path release
          Get-ChildItem .
          Move-Item -Path ChokuRando-linux-x64.zip -Destination release/ChokuRando-linux-v${{ inputs.version }}.zip
          Move-Item -Path ChokuRando-osx-arm64.zip -Destination release/ChokuRando-mac-arm-v${{ inputs.version }}.zip
          Move-Item -Path ChokuRando-osx-x64.zip -Destination release/ChokuRando-mac-intel-v${{ inputs.version }}.zip
          Move-Item -Path ChokuRando-win-x64.zip -Destination release/ChokuRando-windows-v${{ inputs.version }}.zip
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ChokuRando v${{ inputs.version }}
          tag_name: ${{ inputs.version }}
          prerelease: false
          generate_release_notes: false
          files: release/*
          body: |
            ${{ inputs.releaseNotes }}

